baseURL: /
title: "GroSport: Events"
theme: github.com/razonyang/hugo-theme-bootstrap
copyright: 'Copyright © 2016-{year} Лыжное сообщество. All Rights Reserved.'
defaultContentLanguage: ru-ru
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
disableLanguages:
 - fr
 - zh-cn
 - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/

# module:
  # proxy: https://goproxy.cn
